services:
  # 1. Spring Boot backend (connected to Alibaba Cloud RDS)
  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

      # Datasource (MySQL RDS)
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}

      # JPA DDL strategy: validate / update
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

      # Flyway uses spring.datasource config
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_CLEAN_ON_VALIDATION_ERROR=true
    networks:
      - proj-net

  # 2. Python FastAPI Agent (shares the same RDS)
  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - proj-net

  # 3. Vue frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - proj-net

networks:
  proj-net:
    driver: bridge
